version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api


  mysql:
    image: mysql:8.0.17
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testapp
    ports:
      - "3308:3306"
