version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    expose:
      - 3000

  db:
    image: mysql:latest
    restart: always
    container_name: db
    environment:
      MYSQL_USER: lizee
      MYSQL_PASSWORD: lizeezerty
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product
    ports:
      - "3306:3306"
    expose:
      - 3306
